### PR TITLE
Update dfdsdk/aws-inventory-orchestrator Docker tag to v0.0.57

### PR DESCRIPTION
**Pull request by devex-sa**
This PR contains the following updates:

| Package | Update | Change |
|---|---|---|
| dfdsdk/aws-inventory-orchestrator | patch | `0.0.53` -> `0.0.57` |

---

### Configuration

📅 **Schedule**: Branch creation - At any time (no schedule defined), Automerge - At any time (no schedule defined).

🚦 **Automerge**: Disabled by config. Please merge this manually once you are satisfied.

♻ **Rebasing**: Whenever PR becomes conflicted, or you tick the rebase/retry checkbox.

🔕 **Ignore**: Close this PR and you won't be reminded about this update again.

---

 - [ ] If you want to rebase/retry this PR, check this box

---

This PR has been generated by [Renovate Bot](https://togithub.com/renovatebot/renovate).

### CODE REVIEW

**Comment by devex-sa** [comment]
# CodeScene PR Check Disabled

This PR Integration provider has been deprecated and removed. Please configure the GitHub App Integration provider in CodeScene.

**Comment by devex-sa** [comment]
# CodeScene PR Check Disabled

This PR Integration provider has been deprecated and removed. Please configure the GitHub App Integration provider in CodeScene.

**Comment by devex-sa** [comment]
# CodeScene PR Check Disabled

This PR Integration provider has been deprecated and removed. Please configure the GitHub App Integration provider in CodeScene.

**Comment by devex-sa** [comment]
# CodeScene PR Check Disabled

This PR Integration provider has been deprecated and removed. Please configure the GitHub App Integration provider in CodeScene.

**Review by avnes — DISMISSED** [review]

**Comment by devex-sa** [comment]
# CodeScene PR Check Disabled

This PR Integration provider has been deprecated and removed. Please configure the GitHub App Integration provider in CodeScene.

**Comment by devex-sa** [comment]
# CodeScene PR Check Disabled

This PR Integration provider has been deprecated and removed. Please configure the GitHub App Integration provider in CodeScene.

**Comment by devex-sa** [comment]
# CodeScene PR Check Disabled

This PR Integration provider has been deprecated and removed. Please configure the GitHub App Integration provider in CodeScene.

**Review by avnes — APPROVED** [review]

**Pull request merged**
